-- migrate:up 

INSERT INTO formatos_pago (id, nombre) VALUES (1, 'AUTOPLAN');
INSERT INTO formatos_pago (id, nombre) VALUES (2, 'AUTOPLAN VB ENTREGA+BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (3, 'BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (4, 'BBVA BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (5, 'BBVA BCP INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (6, 'BBVA BCP INTBK SCTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (7, 'BBVA BCP INTERBANK');
INSERT INTO formatos_pago (id, nombre) VALUES (8, 'BBVA BCP ITBK');
INSERT INTO formatos_pago (id, nombre) VALUES (9, 'BBVA BCP ITBK NIUBIZ');
INSERT INTO formatos_pago (id, nombre) VALUES (10, 'BBVA BCP SCTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (11, 'BBVA IBK BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (12, 'BBVA INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (13, 'BBVA INTBK BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (14, 'BBVA INTERBANK');
INSERT INTO formatos_pago (id, nombre) VALUES (15, 'BBVA ITBK');
INSERT INTO formatos_pago (id, nombre) VALUES (16, 'BBVA NIUBIZ');
INSERT INTO formatos_pago (id, nombre) VALUES (17, 'BBVA SCOTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (18, 'BBVA SCOTIABANK');
INSERT INTO formatos_pago (id, nombre) VALUES (19, 'BBVA SCOTIABANK MAF');
INSERT INTO formatos_pago (id, nombre) VALUES (20, 'BBVA SCTBK BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (21, 'BBVA VISA');
INSERT INTO formatos_pago (id, nombre) VALUES (22, 'BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (23, 'BCP BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (24, 'BCP BBVA INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (25, 'BCP BBVA MAF');
INSERT INTO formatos_pago (id, nombre) VALUES (26, 'BCP INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (27, 'BCP INTBK FONBIENES');
INSERT INTO formatos_pago (id, nombre) VALUES (28, 'BCP INTBK NIUBIZ');
INSERT INTO formatos_pago (id, nombre) VALUES (29, 'BCP INTERBANK');
INSERT INTO formatos_pago (id, nombre) VALUES (30, 'BCP INTERBANK SCOTIABANK BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (31, 'BCP ITBK');
INSERT INTO formatos_pago (id, nombre) VALUES (32, 'BCP ITBK NIUBIZ');
INSERT INTO formatos_pago (id, nombre) VALUES (33, 'BCP NIUBIZ');
INSERT INTO formatos_pago (id, nombre) VALUES (34, 'BCP NIUBIZ+AUTOPLAN PEDIR VB');
INSERT INTO formatos_pago (id, nombre) VALUES (35, 'BCP SANTANDER');
INSERT INTO formatos_pago (id, nombre) VALUES (36, 'BCP SCOTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (37, 'BCP SCOTIABANK');
INSERT INTO formatos_pago (id, nombre) VALUES (38, 'BCP SCTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (39, 'BCP SCTBK INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (40, 'BCP VISA');
INSERT INTO formatos_pago (id, nombre) VALUES (41, 'BCP VISA+PANDERO');
INSERT INTO formatos_pago (id, nombre) VALUES (42, 'BCP+AUTOPLAN');
INSERT INTO formatos_pago (id, nombre) VALUES (43, 'BCP+AUTOPLAN PEDIR VB PARA ENTREGA');
INSERT INTO formatos_pago (id, nombre) VALUES (44, 'BCP+MAQUIMAS');
INSERT INTO formatos_pago (id, nombre) VALUES (45, 'BCP+NIUBIZ');
INSERT INTO formatos_pago (id, nombre) VALUES (46, 'BCP+PANDERO');
INSERT INTO formatos_pago (id, nombre) VALUES (47, 'CREDITO BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (48, 'CREDITO INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (49, 'CREDITO VEHICULAR BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (50, 'CREDITO VEHICULAR BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (51, 'CSCTBK BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (52, 'IBK');
INSERT INTO formatos_pago (id, nombre) VALUES (53, 'INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (54, 'INTBK BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (55, 'INTBK BBVA BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (56, 'INTBK BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (57, 'INTBK BCP BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (58, 'INTBK SANTANDER');
INSERT INTO formatos_pago (id, nombre) VALUES (59, 'INTERBANK');
INSERT INTO formatos_pago (id, nombre) VALUES (60, 'INTERBANK BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (61, 'INTERBANK BBVA BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (62, 'INTERBANK BBVA MAF');
INSERT INTO formatos_pago (id, nombre) VALUES (63, 'INTERBANK BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (64, 'INTERBANK BCP BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (65, 'INTERBANK NIUBIZ');
INSERT INTO formatos_pago (id, nombre) VALUES (66, 'INTERBANK VISA');
INSERT INTO formatos_pago (id, nombre) VALUES (67, 'ITBK');
INSERT INTO formatos_pago (id, nombre) VALUES (68, 'LEASING BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (69, 'LEASING BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (70, 'LEASING INTERBANK');
INSERT INTO formatos_pago (id, nombre) VALUES (71, 'LEASING SCOTIABANK');
INSERT INTO formatos_pago (id, nombre) VALUES (72, 'LEASING SCTBK BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (73, 'MAF');
INSERT INTO formatos_pago (id, nombre) VALUES (74, 'MAF BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (75, 'MAF BBVA BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (76, 'MAF BBVA NIUBIS');
INSERT INTO formatos_pago (id, nombre) VALUES (77, 'MAF BCP BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (78, 'MAF INTBK BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (79, 'MAF+BBVA BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (80, 'MAF+BBVA BCP INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (81, 'MAF+BBVA INTBK BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (82, 'MAF+BCP BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (83, 'MAQUIMAS');
INSERT INTO formatos_pago (id, nombre) VALUES (84, 'MAQUIMAS PEDIR PERMISO');
INSERT INTO formatos_pago (id, nombre) VALUES (85, 'MAQUISITEMA BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (86, 'NIUBIZ');
INSERT INTO formatos_pago (id, nombre) VALUES (87, 'NIUBIZ BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (88, 'NIUBIZ BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (89, 'NIUBIZ IBK');
INSERT INTO formatos_pago (id, nombre) VALUES (90, 'NIUBIZ SCOTIABANK');
INSERT INTO formatos_pago (id, nombre) VALUES (91, 'NIUBIZ+RETOMA');
INSERT INTO formatos_pago (id, nombre) VALUES (92, 'PANDERO');
INSERT INTO formatos_pago (id, nombre) VALUES (93, 'PANDERO VISA FONBIENES');
INSERT INTO formatos_pago (id, nombre) VALUES (94, 'PEDIR VB FONBIENES');
INSERT INTO formatos_pago (id, nombre) VALUES (95, 'PEDIR VB PANDERO+BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (96, 'PEDIR VB TOTAL');
INSERT INTO formatos_pago (id, nombre) VALUES (97, 'PROMOTORA OPCION+BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (98, 'RETOMA');
INSERT INTO formatos_pago (id, nombre) VALUES (99, 'RETOMA BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (100, 'RETOMA BBVA INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (101, 'RETOMA BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (102, 'RETOMA BCP AUTOPLAN PEDI VB');
INSERT INTO formatos_pago (id, nombre) VALUES (103, 'RETOMA BCP ITB NIUBIZ');
INSERT INTO formatos_pago (id, nombre) VALUES (104, 'RETOMA BCP NIUBIZ');
INSERT INTO formatos_pago (id, nombre) VALUES (105, 'RETOMA CREDITO VEHICULAR BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (106, 'RETOMA FORD');
INSERT INTO formatos_pago (id, nombre) VALUES (107, 'RETOMA INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (108, 'RETOMA INTERBANK');
INSERT INTO formatos_pago (id, nombre) VALUES (109, 'RETOMA MAF BBVA BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (110, 'RETOMA NIUBIZ');
INSERT INTO formatos_pago (id, nombre) VALUES (111, 'RETOMA NIUBIZ BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (112, 'RETOMA SANTANDER');
INSERT INTO formatos_pago (id, nombre) VALUES (113, 'RETOMA SANTANDER BBVA BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (114, 'RETOMA SANTANDER BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (115, 'RETOMA SANTANDER INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (116, 'RETOMA SCOTIABANK');
INSERT INTO formatos_pago (id, nombre) VALUES (117, 'RETOMA SCTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (118, 'RETOMA VISA');
INSERT INTO formatos_pago (id, nombre) VALUES (119, 'RETOMA+BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (120, 'RETOMA+BBVA BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (121, 'RETOMA+BBVA SCTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (122, 'RETOMA+BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (123, 'RETOMA+BCP BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (124, 'RETOMA+BCP INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (125, 'RETOMA+BCP ITBK');
INSERT INTO formatos_pago (id, nombre) VALUES (126, 'RETOMA+BCP PEDIR VB MAQUIMAS');
INSERT INTO formatos_pago (id, nombre) VALUES (127, 'RETOMA+BCP SCTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (128, 'RETOMA+BCP VISA');
INSERT INTO formatos_pago (id, nombre) VALUES (129, 'RETOMA+BCP+SANTANDER');
INSERT INTO formatos_pago (id, nombre) VALUES (130, 'RETOMA+CREDITO BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (131, 'RETOMA+CREDITO VEHICULAR BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (132, 'RETOMA+CREDITO VEHICULAR BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (133, 'RETOMA+INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (134, 'RETOMA+INTERBANK');
INSERT INTO formatos_pago (id, nombre) VALUES (135, 'RETOMA+INTERBANK BCP VISA');
INSERT INTO formatos_pago (id, nombre) VALUES (136, 'RETOMA+LEASING BANBIF');
INSERT INTO formatos_pago (id, nombre) VALUES (137, 'RETOMA+MAF BCP BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (138, 'RETOMA+NIUBIZ');
INSERT INTO formatos_pago (id, nombre) VALUES (139, 'RETOMA+NIUBIZ SCOTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (140, 'RETOMA+SANTANDER');
INSERT INTO formatos_pago (id, nombre) VALUES (141, 'RETOMA+SANTANDER BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (142, 'RETOMA+SANTANDER BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (143, 'RETOMA+SANTANDER BCP BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (144, 'RETOMA+SANTANDER IBK');
INSERT INTO formatos_pago (id, nombre) VALUES (145, 'RETOMA+SANTANDER ITBK');
INSERT INTO formatos_pago (id, nombre) VALUES (146, 'RETOMA+SANTANDER SCOTIABANK');
INSERT INTO formatos_pago (id, nombre) VALUES (147, 'RETOMA+SCOTIABANK');
INSERT INTO formatos_pago (id, nombre) VALUES (148, 'RETOMA+SCTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (149, 'RETOMA+SCTBK INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (150, 'RETOMA+VISA');
INSERT INTO formatos_pago (id, nombre) VALUES (151, 'RETOMA+VISA BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (152, 'SANTANDER');
INSERT INTO formatos_pago (id, nombre) VALUES (153, 'SANTANDER BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (154, 'SANTANDER BBVA BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (155, 'SANTANDER BBVA BCP+RETOMA');
INSERT INTO formatos_pago (id, nombre) VALUES (156, 'SANTANDER BBVA SCTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (157, 'SANTANDER BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (158, 'SANTANDER BCP BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (159, 'SANTANDER BCP BBVA SCTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (160, 'SANTANDER BCP ITB');
INSERT INTO formatos_pago (id, nombre) VALUES (161, 'SANTANDER BCP ITBK');
INSERT INTO formatos_pago (id, nombre) VALUES (162, 'SANTANDER BCP VISA');
INSERT INTO formatos_pago (id, nombre) VALUES (163, 'SANTANDER INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (164, 'SANTANDER INTBK BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (165, 'SANTANDER INTBK VISA');
INSERT INTO formatos_pago (id, nombre) VALUES (166, 'SANTANDER INTERBANK');
INSERT INTO formatos_pago (id, nombre) VALUES (167, 'SANTANDER ITBK');
INSERT INTO formatos_pago (id, nombre) VALUES (168, 'SANTANDER NIUBIZ');
INSERT INTO formatos_pago (id, nombre) VALUES (169, 'SANTANDER NIUBIZ BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (170, 'SANTANDER NIUBIZ BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (171, 'SANTANDER RETOMA SCOTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (172, 'SANTANDER RETOMA+BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (173, 'SANTANDER SCTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (174, 'SANTANDER SCTBK BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (175, 'SANTANDER VISA');
INSERT INTO formatos_pago (id, nombre) VALUES (176, 'SANTANDER+BBVA SCOT');
INSERT INTO formatos_pago (id, nombre) VALUES (177, 'SANTANDER+BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (178, 'SANTANDER+BCP BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (179, 'SANTANDER+BCP INTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (180, 'SANTANDER+BCP SCTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (181, 'SANTANDER+INTERBANK');
INSERT INTO formatos_pago (id, nombre) VALUES (182, 'SANTANDER+NIUBIZ');
INSERT INTO formatos_pago (id, nombre) VALUES (183, 'SANTANDER+RETOMA');
INSERT INTO formatos_pago (id, nombre) VALUES (184, 'SANTANDER+RETOMA BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (185, 'SANTANDER+RETOMA SCOT');
INSERT INTO formatos_pago (id, nombre) VALUES (186, 'SANTANDER+SCOT BBVA');
INSERT INTO formatos_pago (id, nombre) VALUES (187, 'SANTANDER+SCTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (188, 'SCOTBK BBVA BCP');
INSERT INTO formatos_pago (id, nombre) VALUES (189, 'SCOTBK BCP+PANDERO');
INSERT INTO formatos_pago (id, nombre) VALUES (190, 'SCOTIABANK');
INSERT INTO formatos_pago (id, nombre) VALUES (191, 'SCOTIABANK BBVA INTERBANK');
INSERT INTO formatos_pago (id, nombre) VALUES (192, 'SCOTIABANK SANTANDER');
INSERT INTO formatos_pago (id, nombre) VALUES (193, 'SCTBK');
INSERT INTO formatos_pago (id, nombre) VALUES (194, 'VISA');
INSERT INTO formatos_pago (id, nombre) VALUES (195, 'VISA NIUBIZ');

-- migrate:down 

DELETE FROM formatos_pago;